export { default as Home } from "./Home.js";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Routines } from "./Routines";
export { default as Activities } from "./Activities";
export { default as RoutineForm } from "./RoutineForm";
export { default as MyRoutines } from "./MyRoutines";
export { default as RoutineView } from "./RoutineView";
export { default as AddActivityToRoutineForm } from "./AddActivityToRoutineForm"